version = "Two"
edition = "2021"
use_small_heuristics = "Max"
merge_derives = false
error_on_line_overflow = true
error_on_unformatted = true
binop_separator = "Back"
brace_style = "PreferSameLine"
combine_control_expr = true
control_brace_style = "AlwaysSameLine"
fn_params_layout = "Vertical"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
tab_spaces = 2
max_width = 80
imports_granularity = "One"
group_imports = "StdExternalCrate"
trailing_comma = "Never"
